name: Publish to npm

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: 'https://registry.npmjs.com'

            - name: 'Install dependencies'
              run: yarn install

            - name: 'Build'
              run: yarn build

            - name: 'Publish'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
